sudo: required
dist: trusty
os:
    - linux
    - osx
osx_image: xcode8.2

addons:
    apt:
        packages: &default_packages
            - automake
            - autoconf
            - bison
            - flex
            - libtool
            - libc++-dev
            - build-essential
            - libboost-all-dev
            - libevent-dev
            - libssl-dev
            - libcurl4-openssl-dev
            - libdouble-conversion-dev
            - thrift-compiler
            - make
            - pkg-config
            - tree

language: cpp
cache: ccache

python:
    - "2.7"

env:
    global:
        - CMAKE_VERSION=3.7.2

matrix:
  include:
    - os: osx
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - *default_packages
            - g++-5
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - *default_packages
            - clang-3.8
          sources: *sources

before_script:
    - .travis/install-dependencies.sh

script:
    - mkdir build && cd build && rm -rf *
    - echo travis_fold:start:cmake CMake configure
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ../cmake-$CMAKE_VERSION-Linux-x86_64/bin/cmake .. ;fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake .. -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl ;fi
    - echo travis_fold:end:cmake
    - make && make test

after_failure:
    - echo `pwd`
    - cat externals/src/Folly/folly/config.log
    - cat externals/src/Thrift/config.log
    - tree -h

cache:
  ccache: true
  directories:
    - cmake-$CMAKE_VERSION-Linux-x86_64
