sudo: required
dist: trusty
services:
    - docker
os:
    - linux
    - osx
osx_image: xcode8.2

addons:
    apt:
        packages:
            - automake
            - autoconf
            - bison
            - flex
            - libtool
            - build-essential
            - libboost-dev
            - libboost-filesystem-dev
            - libboost-program-options-dev
            - libboost-system-dev
            - libboost-thread-dev
            - libboost-regex-dev
            - libboost-test-dev
            - libevent-dev
            - libssl-dev
            - libcurl4-openssl-dev
            - libdouble-conversion-dev
            - thrift-compiler
            - make
            - pkg-config
            - tree

language: cpp
cache: ccache
compiler:
    - clang
    - gcc

python:
    - "2.7"

env:
    global:
        - CMAKE_VERSION=3.7.2

before_script:
    - .travis/install-dependencies.sh

script:
    - mkdir build && cd build && rm -rf *
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ../cmake-$CMAKE_VERSION-Linux-x86_64/bin/cmake .. ;fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake .. -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl ;fi
    - make && make test

after_failure:
    - echo `pwd`
    - cat externals/src/folly/folly/config.log
    - cat externals/src/thrift/config.log
    - tree -h

cache:
  ccache: true
  directories:
    - cmake-$CMAKE_VERSION-Linux-x86_64
