sudo: required

os:
    - linux
    - osx

addons:
    apt:
        packages:
            - libffi-dev
            - libssl-dev
            - tree

language: cpp

compiler:
    - clang
    - gcc

python:
    - "2.7"

install:
    - pip install requests[security]
    - pip install conan

script:
    - scons

after_failure:
    - echo `pwd`
    - tree -h