sudo: required

dist: trusty

services:
    - docker

os:
    - linux
    - osx

addons:
    apt:
        packages:
            - automake
            - bison
            - flex
            - build-essential
            - clang
            - cmake
            - g++
            - libboost-dev
            - libboost-filesystem-dev
            - libboost-program-options-dev
            - libboost-system-dev
            - libboost-test-dev
            - libevent-dev
            - libssl-dev
            - libtool
            - make
            - pkg-config
            - curl
            - tree

language: cpp

compiler:
    - clang
    - gcc

python:
    - "2.7"

env:
    global:
        - THRIFT_VERSION=0.10.0
        - RDKAFKA_VERSION=0.9.4

install:
    - pip install --upgrade pip
    - pip install conan

before_script:
    - .travis/install-dependencies.sh

script:
    - scons

after_failure:
    - echo `pwd`
    - tree -h