sudo: required
dist: trusty
services:
    - docker
os:
    - linux
    - osx

addons:
    apt:
        packages:
            - automake
            - bison
            - flex
            - build-essential
            - clang
            - g++
            - libboost-dev
            - libboost-filesystem-dev
            - libboost-program-options-dev
            - libboost-system-dev
            - libboost-regex-dev
            - libboost-test-dev
            - libevent-dev
            - libssl-dev
            - libcurl4-openssl-dev
            - libtool
            - make
            - pkg-config
            - tree

language: cpp

compiler:
    - clang
    - gcc

python:
    - "2.7"

env:
    global:
        - CMAKE_VERSION=3.7.2

before_script:
    - .travis/install-dependencies.sh

script:
    - mkdir build && cd build
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ../cmake-$CMAKE_VERSION-Linux-x86_64/bin/cmake .. ;fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake .. ;fi
    - make
    - make test

after_failure:
    - echo `pwd`
    - tree -h

cache:
  ccache: true
  directories:
    - cmake-$CMAKE_VERSION-Linux-x86_64
